# Generated by Django 4.2.2 on 2023-06-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_todo',
            name='Tododone',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='c_todo',
            name='Todoid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
