# Generated by Django 4.2.2 on 2023-06-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_c_todo_tododone_c_todo_todoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c_todo',
            name='id',
        ),
        migrations.AlterField(
            model_name='c_todo',
            name='Todoid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
